# Generated by Django 3.1.5 on 2021-04-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('state', models.IntegerField(choices=[(0, 'OFF'), (1, 'ON')], default=0)),
            ],
        ),
    ]
